### ISSUE TITLE
Ability to import scripts from arbitrary directory 

### ISSUE THREAD

**Issue by johnd0e** [Tampermonkey/tamperdav#11]
Currently:
I specify some url in Tampermonkey, and it dumps all scripts there, with guids as names.

But in fact, I'd prefer some opposite: specify url for Tampermonkey to look for my scripts set, with their actual names.

It's important because scripts are build from source templates.

**Comment by derjanb** [comment]
Feel free to file a pull request which changes TamperDAV to read files from a directory to make Tampermonkey import them on the next sync run

Basic steps: 
 - add a special option to get the folder path
 - find all files ending up on .user.js
 - hash the names and use it as <script ID>
 - create (virtually in memory or on disk) <script ID>.meta.js files with appropriate content for Tampermonkey's sync

**Comment by johnd0e** [comment]
> hash the names and use it as <script ID>

What is hashing algorithm?

**Comment by derjanb** [comment]
Doesn't matter. Tampermonkey uses UUIDs, but every (unique) string should be fine.
