### ISSUE TITLE
What makes tamperdav different from any other WebDAV server?

### ISSUE THREAD

**Issue by flyser** [Tampermonkey/tamperdav#13]
Please clarify the differences or additional features in the readme or project description.

**Comment by Mrnofish** [comment]
I understand this is old, however, the [Tampermonkey FAQ states](https://www.tampermonkey.net/faq.php#Q105):

> contains some proprietary features which speed up the process and allows script editing with your own external editor.

Having not looked at the code, I can't say what those features might be.

**Comment by derjanb** [comment]
From my point of view there is enough explanation:

> A WebDAV-like server to sync Tampermonkey scripts and edit them with an external editor.
>
> WARNING: this is not a 100% WebDAV-compliant server. Many clients should, but don't necessarily have to work!

> "meta-touch": touch a sync entries's meta file automatically to make Tampermonkey start a sync on script changes
