### ISSUE TITLE
A way to store state in an external dir

### ISSUE THREAD

**Issue by x-yuri** [Tampermonkey/tamperdav#20]
I now have it installed in `~/Dropbox/TamperDAV`, but I'd prefer to store in Dropbox only the data, not the code.

**Comment by derjanb** [comment]
TamperDAV is/can be used to sync Tampermonkey scripts and their data. If you want to sync a scripts data please use a webdav client to connect to TamperDAV.

**Comment by x-yuri** [comment]
@derjanb I mean that at the moment if I want to store scripts and their data in Dropbox, I have to store TamerDAV there as well. That is, no way to tell TamperDAV to store data in a custom/external directory.

**Comment by derjanb** [comment]
How about using the `path` config option?
