### ISSUE TITLE
Not sync on Windows 10

### ISSUE THREAD

**Issue by silentnox** [Tampermonkey/tamperdav#7]
TamperDAV successfully syncs js files from Tampermonkey, but not changes to local files do not sync back to Tampermonkey.

**Comment by derjanb** [comment]
Can not reproduce. Everything is working fine here.  https://streamable.com/s/lbixx/cphpee

**Comment by silentnox** [comment]
Now it's working as intended. Not shure where's difference.

**Comment by derjanb** [comment]
You have to make sure TamperDAV is running when Tampermonkey is started. 

> Notes:
> 
> in order to allow Tampermonkey to use the full TamperDAV feature set, please make sure TamperDAV is running when Tampermonkey is started.
