### ISSUE TITLE
Option to disable dialog library

### ISSUE THREAD

**Issue by Nils-1st-retail** [Tampermonkey/tamperdav#8]
Hi,

I had a bit of trouble getting the server to run on my linux VM.
The problem ended up being the dialog library. This library expects to find a display to show the dialog on. 
Since I'm running the server on a VM there's no display and the app crashed with an error 

> Error: spawn zenity ENOENT

I ended up removing the couple of lines using the dialog library, since the same places already had console.log statements, but it would be nice to have an option in the config to make the dialogs optional, If you run the server on a VM or only want the console printouts.

Otherwise great work, using this server setup is quite a bit easier than the custom sync setup I had running before this. :)

**Comment by johnd0e** [comment]
Actually you can disable dialog warning:
```
node server.js no-auth-warning
```
You can put it to `config.json` as well:
```config.json
{
    "path": "dav",
    "meta-touch": true,
    "open-in-editor": true,
    "no-auth-warning": true
}
```

But for other errors dialog will be displayed.
And I agree that no-dialog config option would be useful.
